version = 3
final_space = true

[palette]
  base = '#303446'
  blue = '#8caaee'
  crust = '#232634'
  flamingo = '#eebebe'
  green = '#a6d189'
  lavender = '#babbf1'
  mantle = '#292c3c'
  maroon = '#ea999c'
  mauve = '#ca9ee6'
  overlay_0 = '#737994'
  overlay_1 = '#838ba7'
  overlay_2 = '#949cbb'
  peach = '#ef9f76'
  pink = '#f4b8e4'
  red = '#e78284'
  rosewater = '#f2d5cf'
  sapphire = '#85c1dc'
  sky = '#99d1db'
  subtext_0 = '#a5adce'
  subtext_1 = '#b5bfe2'
  surface_0 = '#414559'
  surface_1 = '#51576d'
  surface_2 = '#626880'
  teal = '#81c8be'
  text = '#c6d0f5'
  yellow = '#e5c890'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .Path }}'
    foreground = 'p:blue'
    type = 'path'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .Behind 0 }} ⇣{{ end }}{{ if gt .Ahead 0 }} ⇡{{ end }}'
    foreground = 'p:surface_2'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ if .Venv }} {{ .Venv }}{{end}}'
    foreground = 'p:surface_2'
    type = 'python'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .FormattedMs }}'
    foreground = 'p:yellow'
    type = 'executiontime'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '❯'
    background = 'transparent'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:mauve{{end}}']
